[RadioNetwork]
name=1
nameID=1
description=
descriptionId=
icon=coui://extendedradio/CustomRadios/1/network.svg
allowAds=true
[RadioChannel]
name=2
nameID=2
description=
icon=coui://extendedradio/CustomRadios/1/2/channel.svg
[Program]
name=3
description=
startTime=00:00
endTime=00:00
loopProgram=true
pairIntroOutro=false
[Segment]
clipsCap=1
